### ISSUE TITLE
basecall group in fast5 output

### ISSUE THREAD

**Issue by wentski** [nanoporetech/pyguppyclient#10]
Hello, 
Apologies if this is the incorrect place to post this but I am struggling to find any answers. I am using a downstream analysis tool which uses basecalled fast5 files as input. By default, it searched for the basecall_template data in the Basecall_1D_000 group, however the fast5 files I have produced with guppy stores the basecall_template data in Basecall_1D_001. So my question is, is there a way to specify which group of the fast5 file to store the basecalling data? Or to retrospectively change it?

This is far from my area of expertise so any help would be greatly appreciated.

**Comment by fbrennen** [comment]
Hi @wentski -- by design, when new basecall sections are written into fast5 files they are always appended, with new groups created as necessary; this means that existing data does not get overwritten. If your analysis tool does not allow the `Basecall_1D_XXX` section to be manually specified, then your best bet would be to clean out the original fast5 files (to remove existing basecall groups) and then re-basecall them. You can do this using either [fast5_api's sanitize option](https://github.com/nanoporetech/ont_fast5_api#compress_fast5) or with [picopore](https://github.com/scottgigante/picopore) (I'm sure there are other good choices as well -- those are the two that immediately came to mind).

If you have other questions then I would recommend dropping by the [Nanopore Community](https://nanoporetech.com/community) and asking them there.
